version: '3.8'
services:
  zookeeper:
    image: confluentinc/cp-zookeeper:7.2.2
    env_file: local.env
    hostname: zookeeper
    container_name: zookeeper
    ports:
      - ${MAPPED_ZK_PORT:-2181}:2181
    volumes:
      - ./data/zookeeper:/var/lib/zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: "${MAPPED_ZK_PORT:-2181}"
      ZOOKEEPER_TICK_TIME: 2000
    networks:
      - tlnts-network

  broker:
    image: confluentinc/cp-kafka:7.2.2
    env_file: local.env
    hostname: broker
    container_name: broker
    depends_on:
      - zookeeper
    ports:
      - ${KAFKA_BROKER_PORT:-9092}:9092
    volumes:
      - ./data/broker:/var/lib/kafka/data/
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: "zookeeper:${MAPPED_ZK_PORT:-2181}"
      KAFKA_INTER_BROKER_LISTENER_NAME: "INTERNAL"
      KAFKA_LISTENERS: "INTERNAL://broker:29092,EXTERNAL://localhost:${KAFKA_BROKER_PORT:-9092}"
      KAFKA_ADVERTISED_LISTENERS: "INTERNAL://broker:29092,EXTERNAL://localhost:${KAFKA_BROKER_PORT:-9092}"
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: "INTERNAL:PLAINTEXT,EXTERNAL:PLAINTEXT"
      KAFKA_DEFAULT_REPLICATION_FACTOR: 1
    networks:
      - tlnts-network

  broker-init:
    image: confluentinc/cp-kafka:7.2.2
    hostname: broker-init
    container_name: broker-init
    depends_on:
      - broker
    entrypoint: [ '/bin/sh', '-c' ]
    command: |
      "
      sleep 10
      kafka-topics --bootstrap-server broker:29092 --list
      kafka-topics --bootstrap-server broker:29092 --create --if-not-exists --topic NOTIFICATIONS.V1 --replication-factor 1 --partitions 1
      echo -e 'Successfully created the following topics:'
      kafka-topics --bootstrap-server broker:29092 --list
      "
    networks:
      - tlnts-network

  kafdrop:
    image: obsidiandynamics/kafdrop
    env_file: local.env
    hostname: kafka-ui
    container_name: kafka-ui
    depends_on:
      - broker
    ports:
      - ${KAFKA_UI_PORT:-9000}:9000
    environment:
      KAFKA_BROKERCONNECT: "broker:29092"
      JVM_OPTS: "-Xms16M -Xmx48M -Xss180K -XX:-TieredCompilation -XX:+UseStringDeduplication -noverify"
    networks:
      - tlnts-network

  postgres:
    image: postgres:14.7
    env_file: local.env
    hostname: postgres
    container_name: postgres
    ports:
      - ${POSTGRES_PORT:-5432}:5432
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
      - ./data/postgres:/var/lib/postgresql
    environment:
      POSTGRES_USER: "${POSTGRES_USERNAME:-root}"
      POSTGRES_PASSWORD: "${POSTGRES_PASSWORD:-root}"
      POSTGRES_DB: "${POSTGRES_DB:-postgres}"
    networks:
      - tlnts-network

networks:
  tlnts-network:
    driver: bridge
